# Generated by Django 5.0.6 on 2024-09-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app1', '0003_class_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
