# Generated by Django 5.1.1 on 2024-09-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roal', models.CharField(choices=[('developer', 'Developer (Software Development)'), ('designer', 'Designer (UI/UX Design)'), ('project_manager', 'Project Manager (Management)'), ('qa_engineer', 'QA Engineer (Quality Assurance)'), ('devops', 'DevOps (Infrastructure and Automation)'), ('hr', 'HR (Human Resources)'), ('marketing', 'Marketing (Digital Marketing)'), ('sales', 'Sales (Business Development)')], max_length=50)),
                ('domain_name', models.CharField(choices=[('software_development', 'Software Development'), ('design', 'UI/UX Design'), ('management', 'Project Management'), ('qa', 'Quality Assurance'), ('infrastructure', 'Infrastructure'), ('hr_department', 'Human Resources'), ('digital_marketing', 'Digital Marketing'), ('business_development', 'Business Development')], max_length=50)),
                ('project_name', models.CharField(max_length=200)),
            ],
        ),
    ]
